export const IDENTITY_ERROR_CODES = {
  OTP_INVALID: "OTP_INVALID",
  OTP_ATTEMPTS_EXCEEDED: "OTP_ATTEMPTS_EXCEEDED",
  OTP_DELIVERY_FAILED: "OTP_DELIVERY_FAILED",
  PHONE_BELONGS_TO_ARCHIVED_MEMBER: "PHONE_BELONGS_TO_ARCHIVED_MEMBER",
  SESSION_EXPIRED: "SESSION_EXPIRED",
} as const;

export type IdentityErrorCode =
  (typeof IDENTITY_ERROR_CODES)[keyof typeof IDENTITY_ERROR_CODES];
