#!/usr/bin/env bash
# ==============================================================================
# apps/api/deploy/deploy.sh
# Deployment script executed on target EC2 instance via AWS SSM Run Command.
#
# Reference: docs/backend/architecture.md
# Workflow:
#   1. Fetch secrets and config from AWS SSM Parameter Store (/agrawal/<env>/)
#   2. Write environment file (.env.<env>) with 0600 permissions
#   3. Pull new Docker image from Amazon ECR
#   4. Execute 'prisma migrate deploy' using DATABASE_MIGRATION_URL in a one-off container
#      -> If migration fails, the restart is immediately aborted!
#   5. Recreate and restart the application container via Docker Compose
#   6. Verify deterministic health/readiness (/readyz) before marking success
# ==============================================================================
set -euo pipefail

ENV="${1:-}"
IMAGE_URI="${2:-}"

if [[ "${ENV}" != "staging" && "${ENV}" != "production" ]]; then
  echo "Error: Usage: $0 <staging|production> <IMAGE_URI>" >&2
  exit 1
fi

if [[ -z "${IMAGE_URI}" ]]; then
  echo "Error: IMAGE_URI parameter is required." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

AWS_REGION="${AWS_REGION:-ap-south-1}"
ENV_FILE="${SCRIPT_DIR}/.env.${ENV}"
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.${ENV}.yml"

if [[ "${ENV}" == "staging" ]]; then
  PORT="${STAGING_PORT:-3001}"
else
  PORT="${PROD_PORT:-3000}"
fi

echo "======================================================================"
echo "Starting deployment for [${ENV}]"
echo "Image: ${IMAGE_URI}"
echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "======================================================================"

# ------------------------------------------------------------------------------
# 1. Fetch SSM Parameters and assemble .env.<env>
# ------------------------------------------------------------------------------
echo "Fetching parameters from AWS SSM Parameter Store (/agrawal/${ENV}/)..."
SSM_PARAMS=$(aws ssm get-parameters-by-path \
  --path "/agrawal/${ENV}/" \
  --with-decryption \
  --recursive \
  --region "${AWS_REGION}" \
  --query "Parameters[*].[Name,Value]" \
  --output text)

if [[ -z "${SSM_PARAMS}" ]]; then
  echo "CRITICAL ERROR: No parameters retrieved from AWS SSM Parameter Store for path /agrawal/${ENV}/. Aborting deployment." >&2
  exit 1
fi

# Write to temporary file first with restricted permissions
TMP_ENV=$(mktemp)
chmod 600 "${TMP_ENV}"

cat <<EOF > "${TMP_ENV}"
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Environment: ${ENV}
NODE_ENV=production
APP_ENV=${ENV}
PORT=3000
EOF

while IFS=$'\t' read -r param_name param_val; do
  if [[ -n "${param_name}" && -n "${param_val}" ]]; then
    # Strip /agrawal/<env>/ prefix
    var_name="${param_name#/agrawal/${ENV}/}"
    # Format into ENV file
    printf '%s="%s"\n' "${var_name}" "${param_val}" >> "${TMP_ENV}"
  fi
done <<< "${SSM_PARAMS}"
mv "${TMP_ENV}" "${ENV_FILE}"
chmod 600 "${ENV_FILE}"
echo "Environment file ${ENV_FILE} written successfully."

# ------------------------------------------------------------------------------
# 2. Pull Docker image
# ------------------------------------------------------------------------------
echo "Pulling Docker image ${IMAGE_URI}..."
docker pull "${IMAGE_URI}"

# ------------------------------------------------------------------------------
# 3. Database Migration Check (Prisma migrate deploy)
# ------------------------------------------------------------------------------
echo "Executing database migration check..."
# A failed migration must abort the deployment before restarting the container
if ! docker run --rm \
    --name "agrawal-migration-${ENV}-$$" \
    --env-file "${ENV_FILE}" \
    "${IMAGE_URI}" \
    npx prisma migrate deploy --schema prisma/schema --config prisma.config.ts; then
  echo "CRITICAL ERROR: 'prisma migrate deploy' failed! Aborting deployment." >&2
  exit 1
fi
echo "Database migrations applied successfully."

# ------------------------------------------------------------------------------
# 4. Restart container stack via Docker Compose
# ------------------------------------------------------------------------------
echo "Restarting ${ENV} container stack..."
IMAGE_URI="${IMAGE_URI}" docker compose -f "${COMPOSE_FILE}" up -d --force-recreate

# ------------------------------------------------------------------------------
# 5. Deterministic Readiness Verification (/readyz)
# ------------------------------------------------------------------------------
echo "Verifying application readiness at http://127.0.0.1:${PORT}/readyz..."

MAX_ATTEMPTS=20
SLEEP_SECS=3
ATTEMPT=1
READY=0

while [[ ${ATTEMPT} -le ${MAX_ATTEMPTS} ]]; do
  HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:${PORT}/readyz" || echo "000")
  if [[ "${HTTP_STATUS}" == "200" ]]; then
    READY=1
    echo "Service is READY (HTTP 200) on attempt ${ATTEMPT}."
    break
  fi
  echo "Attempt ${ATTEMPT}/${MAX_ATTEMPTS}: HTTP status ${HTTP_STATUS}. Retrying in ${SLEEP_SECS}s..."
  sleep ${SLEEP_SECS}
  ATTEMPT=$((ATTEMPT + 1))
done

if [[ ${READY} -ne 1 ]]; then
  echo "CRITICAL ERROR: Service failed readiness check (/readyz) after ${MAX_ATTEMPTS} attempts." >&2
  docker compose -f "${COMPOSE_FILE}" logs --tail 50
  exit 1
fi

echo "======================================================================"
echo "Deployment for [${ENV}] completed successfully!"
echo "======================================================================"
